### ISSUE TITLE
Error with vsearch in MergeTaxonomy and Orient

### ISSUE THREAD

**Issue by PeetersNi** [KasperSkytte/AutoTax#7]
Hello!

First of all, I would like to thank you for making AutoTax publicly available. I am attempting to recreate the output you generated using your original script which uses <code>USEARCH</code>. At this moment I don’t have the 64-bit version of <code>USEARCH</code> available to me. When I ran your script and arrived at the “Finding taxonomy of best hit in SILVA database”-step the memory limit of the 32-bit process was exceeded. So I changed the command to its <code>VSEARCH</code> counterpart which is: 
For searchTaxDB:
<code>$ vsearch -usearch_global $input -db $database -maxaccepts 0 -maxrejects 0 -top_hits_only -strand plus -id 0 -blast6out $output -threads $MAX_THREADS</code>

For searchTaxDB_typestrain:
<code>$ vsearch -usearch_global $input -db $database -maxaccepts 0 -maxrejects 0 -strand plus -id 0.987 -blast6out $output -threads $MAX_THREADS</code>

The script ran smoothly but when it arrived at the mergeTaxonomy-step I got this output: 
<pre><code>Matching unique query sequences: 6 of 85 (7.06%)
[2021-05-27 13:00:24]: Clustering FLASV's at Species level (98.7% identity)
[2021-05-27 13:00:24]: Clustering FLASV's at Genus level (94.5% identity)
[2021-05-27 13:00:24]: Clustering FLASV's at Family level (86.5% identity)
[2021-05-27 13:00:24]: Clustering FLASV's at Order level (82.0% identity)
[2021-05-27 13:00:25]: Clustering FLASV's at Class level (78.5% identity)
[2021-05-27 13:00:25]: Clustering FLASV's at Phylum level (75.0% identity)
[2021-05-27 13:00:25]: Merging and outputting taxonomy...
No replacement file found, skipping...
Error in S4Vectors:::normarg_names(value, class(x), length(x)) : 
  attempt to set too many names (89) on GroupedIRanges object of length
  85
Calls: names<- -> names<- -> names<- -> names<- -> <Anonymous>
Execution halted</code></pre>

These are the files (three missing) that I've got in the <code>/output</code> folder:
<pre>tax_complete.csv
tax_denovo.csv
tax_SILVA.csv
tax_slv_typestr.csv
tax_typestrains.csv</pre>

I thought that there was something wrong with my own databases. So I changed the databases to the ones you’ve originally used (SILVA_138_SSURef_NR99) and shared here: <link>https://figshare.com/articles/dataset/SILVA132_typestrains_in_ARB_UDB11_format/9994568?file=22790396 </link>

But when I tried to run your script with your original databases I get this error on the orient-step. 
<pre><code>[2021-05-27 13:56:11]: Checking for required R packages and installing if missing...
[2021-05-27 13:56:13]:   - Orienting sequences...
usearch v11.0.667_i86linux32, 4.0Gb RAM (198Gb total), 128 cores
(C) Copyright 2013-18 Robert C. Edgar, all rights reserved.
https://drive5.com/usearch

00:03 2.8Gb   100.0% Rows
00:03 2.8Gb  Reading pointers...done.
00:03 2.9Gb  Reading db seqs...

usearch -orient test/example_data/5K_addon_FLASVs.fa -db /home/genomics/npeeters/AutoTax/refdatabases/SILVA_138_SSURef_NR99_tax_silvaK.udb -fastaout temp/fSSUs_oriented.fa -threads 1

---Fatal error---
ReadStdioFile failed, attempted 754773441 bytes, read 748130870 bytes, errno=0
</pre></code>

Have you encountered this problem before? Is there a way to fix this?

Thank you in advance!

**Comment by KasperSkytte** [comment]
Hi there

Thanks for using AutoTax. I'm sorry that you don't have usearch 64-bit available, I know it's an issue for some as it's non-free and closed source. But I have done some brief tests with implementing vsearch instead of usearch, but there are a few issues with it. For some usearch commands there is not a direct equivalent in vsearch, and if there is, the arguments and options are different. So you cannot just replace the usearch commands with vsearch ones directly. I have made a separate vsearch branch recently to adapt autotax to use vsearch fully (see https://github.com/kasperskytte/autotax/tree/vsearch), but unfortunately it's just hanging at the moment as I am busy with other things (handing in a phd thesis this year). It will take quite an effort to adapt fully to vsearch and the results will not be exactly the same as with usearch, so if you are trying to reproduce that in the article I'm afraid you have to use usearch 64-bit. If you have your own data I don't mind running things for you, I have an idle machine or two.

**Comment by PeetersNi** [comment]
Thank you for your response, right now I am trying to process my own data using VSEARCH implemented in your AutoTax script( if that is ok?). I have to admit it's not an easy task to achieve and some output is indeed different compared to usearch.  The error mergetax was solved by adding <code>--maxhits</code> to searchtaxDB. 

Good luck with your PhD thesis!

**Comment by KasperSkytte** [comment]
Hi again. Of course, it's open source, feel free to adapt however you like. If you get it running with vsearch I'll gladly review a PR to merge. Generally it's just a collection of functions that can each be run independently, of course with assumptions about the structure of the input data. I did it this way mainly to make unit testing easier and to be able to customize it a bit more easily. If you source the script it won't run but just load the functions, so you can include it in another workflow or adapt to your needs. I would recommend using the unit tests to verify the individual steps/functions. If you encounter problems let me know, we definitely had some bumps along the way when developing it. Also some of the comments may not be completely up to date, just FYI.

**Comment by aditi48n** [comment]
Hi. I was also planning on running Autotax with vsearch as I do not have the usearch 64-bit. Have you finished running the unit tests for the vsearch branch you shared a link to? 

Thanks

**Comment by KasperSkytte** [comment]
Hi there. There is not a version of AutoTax based on vsearch available yet, unfortunately. It's up to the community to fork and test, and I'll happily review a PR. There are a few commands that are not available with vsearch (yet), but Torbjørn Rognes is usually quick at responding and implementing new features. The free version of usearch might be sufficient, you can give it a try. Otherwise I can process the data for you if you want.

**Comment by KasperSkytte** [comment]
Just FYI, usearch has now been open-sourced and all versions since v5.2 are now freely available here https://github.com/rcedgar/usearch_old_binaries. Source code is only available for v12 though
